import type { AdminContentSnapshot, ManagedItem, PriceMatrix } from '@/lib/content/types'

function priceMatrix(values: Partial<PriceMatrix> = {}): PriceMatrix {
  return {
    detalCarta: values.detalCarta ?? null,
    detalEstandar: values.detalEstandar ?? null,
    mayoreo3: values.mayoreo3 ?? null,
    mayoreo6: values.mayoreo6 ?? null,
    mayoreo12: values.mayoreo12 ?? null,
  }
}

function createItem(item: Omit<ManagedItem, 'id'> & { id?: string }): ManagedItem {
  return {
    id: item.id ?? crypto.randomUUID(),
    ...item,
  }
}

export const defaultAdminContent: AdminContentSnapshot = {
  site: {
    heroDescription:
      'Crea tu estilo único. Ropa y accesorios personalizados de alta calidad, fabricados en Colombia para todo el mundo.',
    catalogoIntro:
      'Todas nuestras prendas son personalizables con diferentes técnicas según tu presupuesto y cantidad.',
    accesoriosIntro:
      'Cuadros, pósters, gorras, termos y más. Personalizamos cada referencia según tu diseño.',
    outOfCatalogTitle: '¿Buscas algo diferente?',
    outOfCatalogDescription:
      'Si no ves el producto que necesitas, escríbenos y revisamos opciones especiales fuera del catálogo.',
    featuredProductSlugs: ['camiseta', 'hoodie-un-color', 'camiseta-oversize', 'rompevientos'],
  },
  catalog: [
    createItem({
      type: 'catalog',
      slug: 'camiseta',
      nombre: 'Camiseta',
      descripcion: 'Camiseta clásica de calidad premium. Disponible en piel de durazno o algodón 100%.',
      subcategoria: 'camisetas',
      material: 'Piel de durazno / Algodón 100%',
      horma: 'hombre',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: true,
      priceMatrix: priceMatrix({ detalCarta: 34500, detalEstandar: 41500, mayoreo3: 22500, mayoreo6: 21000, mayoreo12: 18500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camiseta-ranglan',
      nombre: 'Camiseta Ranglan',
      descripcion: 'Camiseta ranglan con mangas contrastantes.',
      subcategoria: 'camisetas',
      material: 'Poliéster tacto algodón',
      horma: 'hombre',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix({ detalCarta: 36500, detalEstandar: 41500, mayoreo3: 27500, mayoreo6: 24700, mayoreo12: 22500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camiseta-premium',
      nombre: 'Camiseta Calidad Premium',
      descripcion: 'Camiseta premium en algodón peruano o tela burda.',
      subcategoria: 'camisetas',
      material: 'Algodón peruano / Tela burda',
      horma: 'unisex',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix({ detalCarta: 67500, detalEstandar: 74500, mayoreo3: 45500, mayoreo6: 41500, mayoreo12: 37500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camibuzo',
      nombre: 'Camibuzo',
      descripcion: 'Camibuzo personalizable en piel de durazno o algodón.',
      subcategoria: 'camisetas',
      material: 'Piel de durazno / Algodón 100%',
      horma: 'hombre',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix({ detalCarta: 45500, detalEstandar: 52500, mayoreo3: 37500, mayoreo6: 33500, mayoreo12: 30500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camiseta-polo',
      nombre: 'Camiseta Polo',
      descripcion: 'Camiseta tipo polo en poliéster o algodón Lacoste.',
      subcategoria: 'camisetas',
      material: 'Poliéster / Algodón Lacoste',
      horma: 'hombre',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix({ detalCarta: 42500, detalEstandar: 49500, mayoreo3: 30500, mayoreo6: 28500, mayoreo12: 24500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camiseta-oversize',
      nombre: 'Camiseta Oversize',
      descripcion: 'Camiseta oversize de corte relajado.',
      subcategoria: 'camisetas',
      material: 'Algodón 100% / Piel de durazno',
      horma: 'unisex',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: true,
      priceMatrix: priceMatrix({ detalCarta: 55500, detalEstandar: 62500, mayoreo3: 35500, mayoreo6: 32500, mayoreo12: 30500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'hoodie-un-color',
      nombre: 'Hoodie (Un Color)',
      descripcion: 'Hoodie de calidad premium en algodón perchado.',
      subcategoria: 'hoodies',
      material: 'Algodón perchado',
      horma: 'unisex',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: true,
      priceMatrix: priceMatrix({ detalCarta: 76500, detalEstandar: 83500, mayoreo3: 65500, mayoreo6: 62500, mayoreo12: 58500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'rompevientos',
      nombre: 'Rompevientos',
      descripcion: 'Rompevientos en nylon premium.',
      subcategoria: 'chaquetas',
      material: 'Nylon premium',
      horma: 'unisex',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: true,
      priceMatrix: priceMatrix({ detalCarta: 62500, detalEstandar: 69500, mayoreo3: 40000, mayoreo6: 36500, mayoreo12: 33500 }),
    }),
    createItem({
      type: 'catalog',
      slug: 'camisa-compresiva',
      nombre: 'Camisa Compresiva Deportiva',
      descripcion: 'Camisa compresiva deportiva, disponible solo por cotización.',
      subcategoria: 'deportiva',
      material: 'Poliéster deportivo premium',
      horma: 'hombre',
      soloCotizar: true,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix(),
    }),
  ],
  accessories: [
    createItem({
      type: 'accessory',
      slug: 'cuadro-mdf',
      nombre: 'Cuadro',
      descripcion: 'Cuadro personalizado en MDF.',
      subcategoria: 'decoracion',
      material: 'MDF',
      horma: '',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix(),
    }),
    createItem({
      type: 'accessory',
      slug: 'poster',
      nombre: 'Póster',
      descripcion: 'Póster personalizado en papel o aluminio.',
      subcategoria: 'decoracion',
      material: 'Papel / Aluminio',
      horma: '',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix(),
    }),
    createItem({
      type: 'accessory',
      slug: 'gorras',
      nombre: 'Gorras',
      descripcion: 'Gorras personalizadas.',
      subcategoria: 'gorras',
      material: 'Algodón / Poliéster',
      horma: '',
      soloCotizar: false,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix(),
    }),
    createItem({
      type: 'accessory',
      slug: 'peluches',
      nombre: 'Peluches',
      descripcion: 'Peluches personalizados, solo por cotización.',
      subcategoria: 'otros',
      material: 'Personalizable',
      horma: '',
      soloCotizar: true,
      activo: true,
      imagenUrl: null,
      featured: false,
      priceMatrix: priceMatrix(),
    }),
  ],
  updatedAt: new Date().toISOString(),
}